apiVersion: v1
kind: Service
metadata:
  labels:
    app: metaswapdapp
  name: metaswapdapp-svc
spec:
  ports:
  - port: 8000
    name: http
    protocol: TCP
    targetPort: 80
    nodePort: 35580
  type: NodePort
  selector:
    app: metaswapdapp

